version: '3'
services:
    superslicer-docker:
        container_name: superslicer-docker
        volumes:
            - './data:/data'
        networks:
            - superslic3r
        ports:
            - '8090:8080'
        image: 'pilo1337/superslicer-docker:latest'

networks:
  superslic3r:
